apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  selector:
    app: kubia
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: leelister/webtest:v1.0
        ports:
        - containerPort: 8080


