apiVersion: v1
kind: pod
metadata:
  name: kubia-manual-v2
  labels: 
    creation_metion: manual
    env: prod
spec:
  containers:
  - image: leelister/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP